from typing import List, Optional

from pydantic import BaseModel, Field


# ============================================================
# REPORT ITEM
# ============================================================

class ReportItem(BaseModel):
    date: Optional[str] = None

    doctor: Optional[str] = None

    clinic: Optional[str] = None

    snippet: Optional[str] = None


# ============================================================
# PER REPORT PROFILE
# ============================================================

class PerReportProfile(BaseModel):
    """
    Clinical values extracted from one individual encounter.

    Missing values remain None.

    No clinical defaults are created here.
    """

    date: Optional[str] = None

    doctor: Optional[str] = None

    clinic: Optional[str] = None

    snippet: Optional[str] = None

    age: Optional[int] = None

    # Dataset encoding:
    # 1 = female
    # 2 = male
    gender: Optional[int] = None

    height: Optional[float] = None

    weight: Optional[float] = None

    # Blood pressure
    ap_hi: Optional[int] = None

    ap_lo: Optional[int] = None

    bp: Optional[str] = None

    # Dataset encoding:
    # 1 = normal
    # 2 = above normal
    # 3 = well above normal
    cholesterol: Optional[int] = None

    # Dataset encoding:
    # 1 = normal
    # 2 = above normal
    # 3 = well above normal
    gluc: Optional[int] = None

    glucose: Optional[str] = None

    bmi: Optional[float] = None

    # 0 = no
    # 1 = yes
    smoke: Optional[int] = None

    smoking: Optional[str] = None

    # 0 = no
    # 1 = yes
    alco: Optional[int] = None

    # 0 = no
    # 1 = yes
    active: Optional[int] = None

    history: Optional[str] = None


# ============================================================
# FINAL CONSOLIDATED PROFILE
# ============================================================

class FinalProfile(BaseModel):
    """
    Consolidated patient profile.

    The latest valid value is selected from historical
    encounters.

    Missing values remain None.

    ML imputation happens later inside risk_model.py.
    """

    age: Optional[int] = None

    gender: Optional[int] = None

    height: Optional[float] = None

    weight: Optional[float] = None

    ap_hi: Optional[int] = None

    ap_lo: Optional[int] = None

    bp: Optional[str] = None

    cholesterol: Optional[int] = None

    gluc: Optional[int] = None

    glucose: Optional[str] = None

    bmi: Optional[float] = None

    smoke: Optional[int] = None

    smoking: Optional[str] = None

    alco: Optional[int] = None

    active: Optional[int] = None

    history: Optional[str] = None

    consistent_high_factors: List[str] = Field(
        default_factory=list,
        description=(
            "Fields that remained persistently elevated "
            "across multiple historical encounters."
        ),
    )

    anomalies_flagged: List[str] = Field(
        default_factory=list,
        description=(
            "Sudden spikes, contradictions, or anomalies "
            "detected across encounters."
        ),
    )


# ============================================================
# RISK ANALYSIS
# ============================================================

class RiskAnalysis(BaseModel):
    """
    Output generated by the Random Forest risk model.
    """

    status: Optional[str] = Field(
        default=None,
        description=(
            "Result state: ok or insufficient_data."
        ),
    )

    risk_score: Optional[float] = Field(
        default=None,
        description=(
            "Calculated probability risk score, for example 0.367."
        ),
    )

    risk_level: Optional[str] = Field(
        default=None,
        description=(
            "Risk category: low, medium, or high."
        ),
    )

    top_factors: List[str] = Field(
        default_factory=list,
        description=(
            "Top contributing risk driver names."
        ),
    )

    top_3_factors: List[str] = Field(
        default_factory=list,
        description=(
            "Backward-compatible alias for top factors."
        ),
    )

    missing_fields: List[str] = Field(
        default_factory=list,
        description=(
            "Core fields that blocked a reliable prediction."
        ),
    )

    imputed_fields: List[str] = Field(
        default_factory=list,
        description=(
            "Supplementary fields that were estimated using safe defaults."
        ),
    )

    message: Optional[str] = Field(
        default=None,
        description=(
            "Human-readable result or insufficiency explanation."
        ),
    )


# ============================================================
# PATIENT METADATA
# ============================================================

class PatientMeta(BaseModel):
    id: str

    name: str

    mrn: str

    analyzedAt: Optional[str] = None


# ============================================================
# UPLOAD
# ============================================================

class UploadResponse(BaseModel):
    patient_id: str = Field(
        ...,
        description=(
            "Assigned patient/session identifier "
            "for analysis."
        ),
    )


# ============================================================
# ANALYZE REQUEST
# ============================================================

class AnalyzeRequest(BaseModel):
    patient_id: str = Field(
        ...,
        description=(
            "Patient ID used to retrieve the uploaded "
            "document/session."
        ),
    )


# ============================================================
# FINAL ANALYSIS RESPONSE
# ============================================================

class AnalysisResponse(BaseModel):
    """
    Final payload returned to the frontend.
    """

    status: Optional[str] = Field(
        default=None,
        description=(
            "Result status from the model layer."
        ),
    )

    reports: List[ReportItem] = Field(
        default_factory=list
    )

    final_profile: FinalProfile

    risk: Optional[RiskAnalysis] = None

    explanation: str

    patient_meta: Optional[PatientMeta] = None

    missing_fields: List[str] = Field(
        default_factory=list,
        description=(
            "Fields required to compute a stable score."
        ),
    )

    imputed_fields: List[str] = Field(
        default_factory=list,
        description=(
            "Supplementary fields estimated using defaults."
        ),
    )

    message: Optional[str] = None